// Regression tests against real historical digests, frozen under
// test/fixtures/history/. These were generated by the OLD config (reasoning
// effort "medium", unbounded web search) — they are not "expected output" to
// replay against the API (news content changes daily and can't be
// reproduced), but they are a stable contract: any change to newsSchema()
// or validateNewsData() must not break data shaped like real past output,
// and index.json's manifest of dates must always resolve to a real fixture.
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { CAT_ORDER, validateNewsData } from "../scripts/fetch-news.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = path.join(__dirname, "fixtures");
const HISTORY_FIXTURES_DIR = path.join(FIXTURES_DIR, "history");

const fixtureFiles = fs.readdirSync(HISTORY_FIXTURES_DIR).filter((f) => f.endsWith(".json"));

test("at least one history fixture is present", () => {
  assert.ok(fixtureFiles.length > 0, "expected snapshotted history fixtures under test/fixtures/history/");
});

for (const file of fixtureFiles) {
  test(`fixture ${file} passes validateNewsData()`, () => {
    const data = JSON.parse(fs.readFileSync(path.join(HISTORY_FIXTURES_DIR, file), "utf8"));
    assert.doesNotThrow(() => validateNewsData(data));
  });

  test(`fixture ${file} has exactly 5 articles per category with all required fields`, () => {
    const data = JSON.parse(fs.readFileSync(path.join(HISTORY_FIXTURES_DIR, file), "utf8"));
    for (const key of CAT_ORDER) {
      const cat = data.categories[key];
      assert.equal(cat.articles.length, 5, `${file} category ${key} should have 5 articles`);
      for (const article of cat.articles) {
        assert.equal(article.bullets.length, 3, `${file} ${key} article should have 3 bullets`);
        assert.ok(article.emoji && article.title && article.source && article.url);
      }
    }
  });

  test(`fixture ${file}'s filename matches its internal date field`, () => {
    const data = JSON.parse(fs.readFileSync(path.join(HISTORY_FIXTURES_DIR, file), "utf8"));
    assert.equal(`${data.date}.json`, file);
  });
}

test("fixtures/index.json manifest only references fixtures that exist", () => {
  const manifest = JSON.parse(fs.readFileSync(path.join(FIXTURES_DIR, "index.json"), "utf8"));
  for (const date of manifest.dates) {
    assert.ok(
      fs.existsSync(path.join(HISTORY_FIXTURES_DIR, `${date}.json`)),
      `manifest references ${date} but no matching fixture file exists`
    );
  }
});
